### ISSUE TITLE
compliance checker website down

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/compliance-checker-web#119]
When I browse to https://compliance.ioos.us/index.html I get:
![image](https://github.com/ioos/compliance-checker-web/assets/8480023/fb73c6c4-f1cb-4ed5-806f-f59e08c989f1)

**Comment by MathewBiddle** [comment]
Thanks, looks better now.

**Comment by ocefpaf** [comment]
Do we know for how long it was down from the logs?
