### ISSUE TITLE
Open Error while processing the job using IOOS Compliance Checker

### ISSUE THREAD

**Issue by edesfandiari** [ioos/compliance-checker-web#121]
Recently, my attempts to check few short files using CF 1.6, 1.7, or 1.8 from
https://compliance.ioos.us/index.html keep failing. The .nc files upload successfully but they all fail with 
"Error while processing the job. Job Timed Out" messages! My attempts even fails for same files that were 
successfully checked back in February. I'm using Linux RedHat and have the same issue using both Chrome 
and FireFox.

Also, the 'feedback' does not function either. Sending a note results in
=>
compliance.ioos.us says
An Error has Occurred

Attached is a sample .nc4 file (renamed by adding .csv to get it to upload) which was successfully used before.
Also attached are screen shots of processing and timed out error (takes a long time after a quick and successful upload).
[GiOCEAN_e1.aci_tavg_1dy_glo_L360x181_p27.19980201_1200z.nc4.csv](https://github.com/ioos/compliance-checker-web/files/15471526/GiOCEAN_e1.aci_tavg_1dy_glo_L360x181_p27.19980201_1200z.nc4.csv)
![Screenshot_uploaded_and_processing](https://github.com/ioos/compliance-checker-web/assets/100610812/d1895a52-5025-48ac-9b3e-c4d084cf40f2)
![Screenshot_processing_timed-out](https://github.com/ioos/compliance-checker-web/assets/100610812/1646b463-5854-4eb2-84b3-343792a95df5)

**Comment by edesfandiari** [comment]
Here is the zip version of the .nc4 file:
[GiOCEAN_e1.aci_tavg_1dy_glo_L360x181_p27.19980201_1200z.nc4.zip](https://github.com/ioos/compliance-checker-web/files/15488702/GiOCEAN_e1.aci_tavg_1dy_glo_L360x181_p27.19980201_1200z.nc4.zip)

**Comment by edesfandiari** [comment]
Hello,

The issue with online IOOS Compliance Checker
https://compliance.ioos.us/index.html
 is still unresolved. Can someone please take a look at it?

**Comment by edesfandiari** [comment]
Any thoughts/suggestions regarding this issue with the online IOOS Compliance Checker?

**Comment by mwengren** [comment]
@edesfandiari Thanks for reporting this issue.  Separately, we've been working on addressing some issues with the feedback forms on our site, that might help out with what you reported, but I can't be of much help with the specific issues with the Compliance Checker website functionality.  @benjwadams Any thoughts about this?

**Comment by MathewBiddle** [comment]
I think this is still an issue. Can someone take a look?

![image](https://github.com/ioos/compliance-checker-web/assets/8480023/0fff9de7-f85e-4226-ba52-3164e19ea6c4)

**Comment by mwengren** [comment]
@benjwadams Can you look into the functionality issues with CC Web related to this post?  Or provide a comment about what our plan is to restore the CC Web website back to operational status?  I believe you mentioned in the longer term we need to rewrite aspects of the site, but perhaps the current version can be restored in the meantime.

@nguyandy Can you look into why the Feedback form isn't working on this site?

**Comment by edesfandiari** [comment]
Just tried again and it seems the problem is resolved now. Thank you.

**Comment by ocefpaf** [comment]
@edesfandiari closing this as resolved. Thanks! Please open a new issue if the problem resurfaces.
