### ISSUE TITLE
CC-Web Version #?

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/compliance-checker-web#20]
@lukecampbell - Does the compliance-checker-web have a version #?  Compliance Checker's last major release is V. 2.0.  Has the CC-Web been updated to the V 2.0 release?

**Comment by lukecampbell** [comment]
Yes, it's using the 2.0 version.

**Comment by lukecampbell** [comment]
I will look into including the versions into the web's GUI. There's kind of a topic about this: 
https://github.com/ioos/compliance-checker/issues/133
https://github.com/ioos/compliance-checker/issues/186

**Comment by jbosch-noaa** [comment]
So do we call this current version of CC-web V1.0 or V2.0?  Currently there is no note of a release version of CC-Web on Github. Is there an expected date for release for V2.1?

**Comment by lukecampbell** [comment]
Ideally this week, we have a third party dependency that has some packaging issues that we're waiting on. It's somewhat out of the control of the developers that directly contribute to compliance checker but it's in progress:

https://github.com/ioos/compliance-checker/issues/222

**Comment by jbosch-noaa** [comment]
Cool.  Thanks for the quick response. :)

**Comment by jbosch-noaa** [comment]
@lukecampbell  - ioos/compliance-checker#222 has been closed for a while now.  You released CC-web V1.0 in June.  Is there a plan to do another release in the near future?  If so, I would like us to put attach milestone to it.

**Comment by lukecampbell** [comment]
This was done a while ago.
![screen shot 2016-08-01 at 4 57 14 pm](https://cloud.githubusercontent.com/assets/1155163/17308622/0257360e-5809-11e6-9a85-dcd60cbbb9a7.png)

**Comment by lukecampbell** [comment]
I can't find the specific commit to reference here, but we added the checker versions sometime around March, I think.
