### ISSUE TITLE
OPeNDAP URLs not working

### ISSUE THREAD

**Issue by kwilcox** [ioos/compliance-checker-web#23]
I can't get any OPeNDAP URLs to work.

http://thredds.cencoos.org/thredds/dodsC/cencoos/sensors/Humboldt/sea_water_practical_salinity.nc

```
Error while processing the job.
Exception: Could not understand response code 200 and content-type text/html; charset=UTF-8
```

**Comment by lukecampbell** [comment]
Weird, I got it to work:

http://data.ioos.us/compliance/report/49051440e684edbdc1e3dfac2748baa68cc73535

The report is only valid for a few minutes though.

**Comment by kwilcox** [comment]
Worked after about 10 attempts... is it possible that a stale worker is picking up jobs?  I can get it to fail periodically.
