### ISSUE TITLE
File browse/drag and drop not functioning? 

### ISSUE THREAD

**Issue by mbiddle-nodc** [ioos/compliance-checker-web#26]
Trying to upload a dataset and nothing is happening. I point to the file select the test and hit submit but nothing happens. After a bit, a red bar shows up at the bottom of the page, with no text.

**Comment by lukecampbell** [comment]
Is this still happening?

**Comment by mbiddle-nodc** [comment]
Just got a 'Not Found' error.

**Comment by mbiddle-nodc** [comment]
So, it works with other files. But, for some reason when I download the file http://data.nodc.noaa.gov/thredds/catalog/ghrsst/L4/GLOB/OSPO/Geo_Polar_Blended_Night/2016/126/catalog.html?dataset=ghrsst/L4/GLOB/OSPO/Geo_Polar_Blended_Night/2016/126/20160505000000-OSPO-L4_GHRSST-SSTfnd-Geo_Polar_Blended_Night-GLOB-v02.0-fv01.0.nc and try to use the upload option, it doesn't do anything. 

Is size a consideration here?

**Comment by mbiddle-nodc** [comment]
To note, using the OPeNDAP url (http://data.nodc.noaa.gov/thredds/dodsC/ghrsst/L4/GLOB/OSPO/Geo_Polar_Blended_Night/2016/126/20160505000000-OSPO-L4_GHRSST-SSTfnd-Geo_Polar_Blended_Night-GLOB-v02.0-fv01.0.nc) works fine in the checker...

**Comment by kwilcox** [comment]
It says the max file size is 16MB but your file is ~20MB... that is probably the issue.

**Comment by mbiddle-nodc** [comment]
Right, I'm blind. Thanks for that.

**Comment by lukecampbell** [comment]
We played around with upload sizes and 3MB was too small and 20MB started to take too long to upload which ties up a thread. A feature on the docker for the next release is to upload just the CDL.
