### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by kwilcox** [ioos/compliance-checker-web#32]
Can we get a python 3 compatible version?

**Comment by lukecampbell** [comment]
I'm blocked until the dependencies get fixed
https://github.com/mattupstate/flask-environments/pull/5

**Comment by lukecampbell** [comment]
I can run the project in Python3 without any changes if I patch flask-environments by hand.

**Comment by daf** [comment]
Strongly guessing a project that has no commits to either main branches since 2012 is not going to be merging any PRs.

**Comment by kwilcox** [comment]
That's a 74 line library, including comments and whitespace. Could just copy paste it into the project and fix it locally.
