### ISSUE TITLE
Landing page documentation 

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/compliance-checker-web#62]
@Bobfrat  - I am glad to see that you have been updating the Compliance Checker Web to be in sync with the command line Compliance Checker but there needs to be an explanation on this webpage for those who just stumble upon it or have never used it before.

What is it?
What does it check compliance of?
What version of the Compliance Checker is run on this site?
Link to the Compliance Checker GitHub README file that explains the relationship between this website and the command line version of the software.

**Comment by Bobfrat** [comment]
@jbosch-noaa when you say "this webpage" you mean on the application [homepage](https://data.ioos.us/compliance/index.html) and not the project README file, right?

**Comment by jbosch-noaa** [comment]
Yes, @Bobfrat.  The application homepage. :)

**Comment by Bobfrat** [comment]
I think this is a great idea. Do you want this on the main page or in a separate help page? Might be best if we keep it brief and on the main page so its not hidden.

**Comment by Bobfrat** [comment]
About page is located here https://compliance.ioos.us/about
